"""Add level bonuses and distributed_points

Revision ID: acce14b560e7
Revises: b40b46b63d01
Create Date: 2025-12-02 08:11:12.464384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acce14b560e7'
down_revision: Union[str, Sequence[str], None] = 'b40b46b63d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_slots_slot_id', table_name='user_slots')
    op.drop_index('ix_user_slots_user_id', table_name='user_slots')
    op.drop_table('user_slots')
    op.drop_index('ix_purchased_slots_channel_username', table_name='purchased_slots')
    op.drop_table('purchased_slots')
    op.drop_table('transactions')
    op.drop_table('users')
    op.drop_table('referrals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('referred_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='referrals_pkey'),
    sa.UniqueConstraint('referred_id', name='referrals_referred_id_key')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('free_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payout_bonus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timer_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('current_checkpoint', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('checkpoint_progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ref_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_boost_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('referrer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey')
    )
    op.create_table('purchased_slots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('advertiser_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('channel_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('slot_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('required_shows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_shows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='purchased_slots_pkey')
    )
    op.create_index('ix_purchased_slots_channel_username', 'purchased_slots', ['channel_username'], unique=False)
    op.create_table('user_slots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('slot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subscribed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_slots_pkey')
    )
    op.create_index('ix_user_slots_user_id', 'user_slots', ['user_id'], unique=False)
    op.create_index('ix_user_slots_slot_id', 'user_slots', ['slot_id'], unique=False)
    # ### end Alembic commands ###
